add_library(spdlog STATIC IMPORTED)
set_target_properties(spdlog PROPERTIES 
    IMPORTED_IMPLIB "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/Lib/spdlog.lib"
    INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/Include")