add_library(volk STATIC IMPORTED)
set_target_properties(volk PROPERTIES 
    IMPORTED_LOCATION "${CMAKE_CURRENT_LIST_DIR}/Lib/volk.lib"
    INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_CURRENT_LIST_DIR}/Include"
    IMPORTED_CONFIGURATIONS "Debug;Release")